name: 'Privalyse Privacy Scanner'
description: 'Scan your code for privacy leaks, PII, and GDPR violations.'
author: 'Privalyse'
branding:
  icon: 'shield'
  color: 'blue'
inputs:
  root:
    description: 'Root directory to scan'
    required: false
    default: '.'
  format:
    description: 'Output format (markdown, json, html)'
    required: false
    default: 'markdown'
  output:
    description: 'Output file path'
    required: false
    default: 'scan_results.md'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install Privalyse
      shell: bash
      run: pip install privalyse-cli
      
    - name: Run Privalyse Scanner
      shell: bash
      run: privalyse --root "${{ inputs.root }}" --format "${{ inputs.format }}" --out "${{ inputs.output }}"
